'use strict';

const constants = {
    application: {
        SCHEMA: {
            command: '',
            cpus: 0.1,
            deployment: {
                strategy: 'rolling'
            },
            engine: 'docker',
            env_vars: {},
            health_checks: [],
            id: null,
            image: 'containership/engine',
            memory: 128,
            network_mode: 'bridge',
            privileged: false,
            respawn: true,
            tags: {
                metadata: {}
            },
            volumes: []
        }
    },

    myriad: {
        APPLICATIONS: ['^containership', 'application', '.*'],
        APPLICATION_PREFIX: ['containership', 'application'],
        AUTOGENERATED_VARIABLES: ['^containership', 'variables', 'autogenerated', '.*'],
        AUTOGENERATED_VARIABLES_PREFIX: ['containership', 'variables', 'autogenerated'],
        CLUSTER_ID: ['containership', 'cluster', 'id'],
        CONTAINERS: ['^containership', 'containers', '.*'],
        CONTAINERS_PREFIX: ['containership', 'containers'],
        DELIMITER: '::',
        ENOKEY: 'ENOKEY',
        PLUGINS: ['^containership', 'plugins', '.*'],
        PLUGINS_PREFIX: ['containership', 'plugins'],
        USER_VARIABLES: ['^containership', 'variables', 'user', '.*'],
        USER_VARIABLES_PREFIX: ['containership', 'variables', 'user'],
        VARIABLES: ['^containership', 'variables', '.*'],
        VARIABLES_PREFIX: ['containership', 'variables'],
        TIDE_JOBS: ['containership', 'tide-jobs']
    },

    events: {
        CLUSTER_ID: 'containership.cluster_id',
        RECONCILE: 'containership.reconcile',
        LOAD_CONTAINER: 'containership.load_container',
        UNLOAD_CONTAINER: 'containership.unload_container',
        UPDATE_HOST: 'containership.update_host',
        DELETE_HOST: 'containership.delete_host'
    }
};

for(const key in constants.myriad) {
    if(constants.myriad[key] instanceof Array) {
        constants.myriad[key] = constants.myriad[key].join(constants.myriad.DELIMITER);
    }
}

module.exports = constants;
